language: generic
sudo: required
dist: trusty


matrix:
  fast_finish: true

  include:
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'cmake', 'realpath', 'libbz2-dev', 'zlib1g-dev', 'libexpat1-dev']
      env: CCOMPILER='gcc-6' CXXCOMPILER='g++-6'

    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'cmake', 'realpath', 'libbz2-dev', 'zlib1g-dev', 'libexpat1-dev']
      env: CCOMPILER='gcc-5' CXXCOMPILER='g++-5'

    - os: linux
      addons:
        apt:
          sources: ['llvm-toolchain-precise-3.8']
          packages: ['clang-3.8', 'cmake', 'realpath', 'libbz2-dev', 'zlib1g-dev', 'libexpat1-dev']
      env: CCOMPILER='clang-3.8' CXXCOMPILER='clang++-3.8'

    # Waiting on Travis whitelisting 3.9, see https://github.com/travis-ci/apt-source-whitelist/issues/300


before_install:
  - export CC=${CCOMPILER} CXX=${CXXCOMPILER}

install:
  - ./deps.sh
  - mkdir build
  - pushd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build .
  - popd

script:
  - pushd tests
  - ./check.sh
